spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev   #开发环境
  application:
    name: microservicecloud-config-wmp-dev
---
spring:
  profiles: test   #测试环境
  application:
    name: microservicecloud-config-wmp-test
#格式保存为UTF-8